# Generated by Django 5.2.7 on 2026-01-10 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='following_count',
        ),
    ]
