# Generated by Django 5.2.7 on 2026-01-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_avatar_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Mężczyzna'), ('female', 'Kobieta')], default='', max_length=20),
        ),
    ]
