# Generated by Django 5.2.7 on 2026-01-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Mężczyzna'), ('female', 'Kobieta')], max_length=20, null=True),
        ),
    ]
